apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: auth-service
  labels:
    app: auth-service
    part-of: finance-platform

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auth-service-role
  namespace: auth-service
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-role-binding
  namespace: auth-service
subjects:
- kind: ServiceAccount
  name: auth-service
  namespace: auth-service
roleRef:
  kind: Role
  name: auth-service-role
  apiGroup: rbac.authorization.k8s.io 