server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

log:
  level: "info"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "order_engine"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

nats:
  url: "nats://localhost:4222"

jwt:
  secret: "your-secret-key"  # Change this in production
  expiry_period: 24h

market_data:
  api_key: "your-api-key"  # Change this in production
  base_url: "https://api.market-data-provider.com" 